language: ruby
dist: xenial
bundler_args: "--without deployment"
sudo: required
services: mysql
addons:
  apt:
    packages:
    - haveged
    - google-chrome-stable
    - chromium-chromedriver
cache:
  bundler: true
env:
  global:
  - TZ=Europe/London
  - PATH=$PATH:/usr/lib/chromium-browser/
  - DISPLAY=:99.0
before_install:
- sh -e /etc/init.d/xvfb start
before_script:
- bundle exec rake db:setup
script:
- bundle exec rspec
before_deploy: "./compile-build"
deploy:
  file_glob: true
  skip_cleanup: true
  provider: releases
  api_key:
    secure: BOwjXaDGu8oUTrKZOL/nEvMzn9qQeBbJlp/4udgNg7i02Hxf9q/xcdHDSj2zI2UcZWPBzV7F1BZZeRc8RWMs6YUOJZYj6CCx9rVshlthtky7zZhtUCbtsUKLPcrzuFxa2wg3TccNScng9yU5lb7Amg7cPuI7ZVeqYDeVx9VxwXDnJJ0S4Q6LNK5iFMTxPwaYGoEJQZvLaq/HSRH5smK2uGy1hQzcGa9+Ewk+A9btcJBZUSZ7eR1v1tpJ1dmINHNxiXkdDWcumNWJblcd5gdL0ADNJPoFE9dASaGK95RAJEJzacq0vvyEQ0+ZmOll+HSmmKwicSRtWbAg4Aqr3rSHBEPhBgBdeGj3JgG89PXgrCcAs+9GHYEhsxRp/5xne+gb6ZeAYWITNEnSDI2yQ3pLSO4pYfskSLqzVRCEm7XkvnM+mXtQ3qbwO/FsXnNjAou2okx7yCCenIIVScQTZk2GW/PpIKAB5rPwsRqYHSsbQ7WOa6k7rdrRXQaVVyuTo61zly1HMolz0z6wtMsv/X0F+j9LP4JS/3RouL+NWGOBnS4FkH3tyQ+L39WTk84qe65E02QM+DN/tlFHBLpHoa615zM/xepemmGujKOVNQe4RHReUb1syh8mJUdRAPJuhAdXKzvJBsmNYPsPGmbYJOCTs1Cv166MzzUTqHFpwynMQcU=
  file: release.tar.gz
  on:
    tags: true
    repo: stevieing/sm_workflow_lims
